
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
    ports:
      - "5173:80"
    depends_on:
      - backend



  redis:
    image: redis:7
    ports:
      - "6379:6379"


  celery:
    build: ./backend
    container_name: celery
    command: celery -A src.celery_app.celery worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      PYTHONPATH : /app
    depends_on:
      - redis
    
  celery-beat:
    build: ./backend
    container_name: celery-beat
    command: celery -A src.celery_app.celery beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - celery
    environment:
      PYTHONPATH : /app

volumes:
  pgdata: