version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5433"
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      SECRET_KEY: supersecret
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/app_db
      FRONTEND_URLS: http://localhost:5173
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  redis:
    image: redis:7
    ports:
      - "6379:6379"


  celery:
    build: ./backend
    container_name: celery
    command: celery -A src.celery_app.celery worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app
    depends_on:
      - redis
    
  celery-beat:
    build: ./backend
    container_name: celery-beat
    command: celery -A src.celery_app.celery beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app

volumes:
  pgdata: